name: eye
description: A new Flutter project.

publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  # country_state_city_picker: ^1.2.8
  csc_picker: ^0.2.6
  cupertino_icons: ^1.0.4
  flutter:
    sdk: flutter
  http: ^0.13.4
  sqflite: ^2.0.2

dev_dependencies:
  flutter_launcher_icons: ^0.9.2

  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  fluttertoast: ^8.0.9
  geolocator: ^8.2.0
  google_fonts: ^2.3.1
  shared_preferences: ^2.0.13

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo-1024.jpg"

flutter:

  uses-material-design: true

  assets:
    - assets/images/
